WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Controllers/AdminCategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopNovel.Models;
using PagedList.Core;
using System.Globalization;
using System.IO;
using WebShopNovel.Helpper;
using AspNetCoreHero.ToastNotification.Abstractions;

namespace WebShopNovel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminCategoriesController : Controller
    {
        private readonly WebNovel _context;
        public static string image;
        public INotyfService _notyfService { get; }

        public AdminCategoriesController(WebNovel context, INotyfService notyfService)
        {
            _notyfService = notyfService;
            _context = context;
        }

        // GET: Admin/AdminCategories
        public IActionResult Index(string sortOrder, string currentFilter, string searchStr, int? page)
        {
            var _category = from m in _context.Categories select m;
            //Sort
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["NameSortParm"] = sortOrder == "Name" ? "name_desc" : "Name";
            ViewData["TitleSortParm"] = sortOrder == "Title" ? "title_desc" : "Title";
            ViewData["CurrentSort"] = sortOrder;
            switch (sortOrder)
            {
                case "id_desc":
                    _category = _category.OrderByDescending(p => p.CateId);
                    break;
                case "Name":
                    _category = _category.OrderBy(p => p.CategoryName);
                    break;
                case "name_desc":
                    _category = _category.OrderByDescending(p => p.CategoryName);
                    break;
                case "title_desc":
                    _category = _category.OrderByDescending(p => p.Title);
                    break;
                case "Title":
                    _category = _category.OrderBy(p => p.Title);
                    break;
                case "Disable":
                    _category = _category.OrderBy(p => p.IsPublished);
                    break;
                case "Publish":
                    _category = _category.OrderByDescending(p => p.IsPublished);
                    break;
                default:
                    _category = _category.OrderBy(p => p.CateId);
                    break;
            }

            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                _category = _category.Where(p => p.CateId.ToString().Contains(searchStr) || p.CategoryName.Contains(searchStr) || p.Descriptions.Contains(searchStr) || p.Title.Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 5;
            ViewBag.CurrentPage = pageNo;
            PagedList<Category> models = new PagedList<Category>(_category, pageNo, pageSize);
            return View(models);
        }

        // GET: Admin/AdminCategories/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CateId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // GET: Admin/AdminCategories/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/AdminCategories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CateId,CategoryName,Descriptions,ParentId,Levels,Ordering,IsPublished,ThumbImg,Title,Alias,Cover")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumbImg)
        {
            if (ModelState.IsValid)
            {
                category.CategoryName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(category.CategoryName);
                if (fThumbImg != null)
                {
                    string extennsion = Path.GetExtension(fThumbImg.FileName);
                    image = Utilities.ToUrlFriendly(category.CategoryName) + extennsion;
                    category.ThumbImg = await Utilities.UploadFile(fThumbImg, @"categories", image.ToLower());
                }
                if (string.IsNullOrEmpty(category.ThumbImg)) category.ThumbImg = "thumb-6.jpg";
                category.Alias = Utilities.ToUrlFriendly(category.CategoryName);
                _context.Add(category);
                _notyfService.Success("Thêm thành công!");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            return View(category);
        }

        // POST: Admin/AdminCategories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("CateId,CategoryName,Descriptions,ParentId,Levels,Ordering,IsPublished,ThumbImg,Title,Alias,Cover")] Category category, Microsoft.AspNetCore.Http.IFormFile fThumbImg)
        {
            if (id != category.CateId)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                try
                {
                    category.CategoryName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(category.CategoryName);
                    if (fThumbImg != null)
                    {
                        string extennsion = Path.GetExtension(fThumbImg.FileName);
                        image = Utilities.ToUrlFriendly(category.CategoryName) + extennsion;
                        category.ThumbImg = await Utilities.UploadFile(fThumbImg, @"categories", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(category.ThumbImg)) category.ThumbImg = "thumb-6.jpg";
                    category.Alias = Utilities.ToUrlFriendly(category.CategoryName);
                    _context.Update(category);
                    _notyfService.Success("Sửa thành công!");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CateId))
                    {
                        _notyfService.Error("Lỗi!!!!!!!!!!!!!");
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(category);
        }

        // GET: Admin/AdminCategories/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CateId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/AdminCategories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var category = await _context.Categories.FindAsync(id);
            string imageName = image.ToLower() +
            _context.Categories.Remove(category);
            Utilities.DeleteImage(@"User", imageName);
            _notyfService.Success("Xóa thành công!");
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(int id)
        {
            return _context.Categories.Any(e => e.CateId == id);
        }
    }
}

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminCategories/Create.cshtml
@model WebShopNovel.Models.Category

@{
    ViewData["Title"] = "Thêm danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <form asp-controller="AdminCategories" asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="media align-items-center m-b-15">
                    <div class="avatar avatar-image rounded" style="height: 165px; width: 165px">
                        <img src="assets/images/others/thumb-16.jpg" alt="" id="output" style="border-radius:20px;">
                    </div>
                    <div class="m-l-15">
                        <h4 class="m-b-0">Unknown</h4>
                        <p class="text-muted m-b-0">ID: #Unknown</p>
                    </div>
                </div>
                <div class="m-b-15">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Tạo</span>
                        </button>
                    </div>
                    <div>
                        <a asp-action="Index" class="btn btn-dark">Trở về</a>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="CategoryName" class="control-label"></label>
                            <input asp-for="CategoryName" class="form-control" />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="IsPublished" checked="" />
                                <label for="IsPublished"></label>
                            </div>
                            <label>IsPublished</label>
                        </div>
                        <div class="form-group">
                            <label asp-for="ThumbImg" class="font-weight-semibold">Upload Ảnh</label>
                            <input type="file" name="fThumbImg" asp-for="ThumbImg" class="form-control-file" onchange="loadFile(event)" />
                            <span asp-validation-for="ThumbImg" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card" style="background: #F0BF87">
                    <div class="card-body">
                        <label asp-for="Descriptions" class="control-label" style="font-weight :800"></label>
                        <textarea asp-for="Descriptions" class="summernnote"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/_AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/_AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/_AdminAssets/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $( '.summernnote' ).summernote({
                fontNames: ['Comic Sans MS'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 350,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
    <script>
        var loadFile = function (event) {
            var image = document.getElementById("output");
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
}
@section Styles {
    <link href="~/_AdminAssets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/_AdminAssets/summernote/summernote.css" rel="stylesheet" />
}

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminCategories/Details.cshtml
@model WebShopNovel.Models.Category

@{
    ViewData["Title"] = "Chi tiết danh mục #" + Model.CateId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <div class="page-header no-gutters has-tab">
        <div class="d-md-flex m-b-15 align-items-center justify-content-between">
            <div class="media align-items-center m-b-15">
                @*<div class="avatar avatar-image rounded" style="height: 70px; width: 70px">
                    <img src="~/images/categoties/@Model.ThumbImg" alt="@Model.Title">
                </div>*@
                <div class="m-l-15">
                    <h4 class="m-b-0">@Model.CategoryName</h4>
                    <p class="text-muted m-b-0">ID: @Model.CateId</p>
                </div>
            </div>
            <div class="m-b-15">
                <div class="form-group">
                    <a asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CateId" class="btn btn-primary">
                        <i class="anticon anticon-edit"></i>
                        <span>Sửa</span>
                    </a>
                </div>
                <div>
                    <a asp-action="Index" type="button" class="btn btn-dark">Back to List</a>
                </div>
            </div>
        </div>
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CategoryName)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CategoryName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Descriptions)
            </dt>
            <dd class="col-sm-10">
                @Html.Raw(Model.Descriptions)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ParentId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ParentId)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Levels)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Levels)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Ordering)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Ordering)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IsPublished)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IsPublished)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ThumbImg)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ThumbImg)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Title)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Title)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Alias)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Alias)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Cover)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Cover)
            </dd>
        </dl>
    </div>
</div>

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminCategories/Edit.cshtml
@model WebShopNovel.Models.Category

@{
    ViewData["Title"] = "Chỉnh sửa danh mục #" + Model.CateId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="main-content">
    <form asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@Model.CateId" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="CateId" />
        <input type="hidden" asp-for="ThumbImg" />
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="media align-items-center m-b-15">
                    <div class="avatar avatar-image rounded" style="height: 165px; width: 165px">
                        <img src="~/images/categories/@Model.ThumbImg" alt="@Model.Title" id="output">
                    </div>
                    <div class="m-l-15">
                        <h4 class="m-b-0">@Model.CategoryName</h4>
                        <p class="text-muted m-b-0">ID: #@Model.CateId</p>
                    </div>
                </div>
                <div class="m-b-15">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                    </div>
                    <div>
                        <a asp-action="Index" type="button" class="btn btn-dark">Back to List</a>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="CategoryName" class="control-label"></label>
                            <input asp-for="CategoryName" class="form-control" />
                            <span asp-validation-for="CategoryName" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label"></label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            @if (Model.IsPublished)
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsPublished" checked="" />
                                    <label for="IsPublished"></label>
                                </div>
                            }
                            else
                            {
                                <div class="switch m-r-10">
                                    <input type="checkbox" asp-for="IsPublished" />
                                    <label for="IsPublished"></label>
                                </div>
                            }
                            <label>IsPubished</label>
                        </div>
                        <div class="form-group">
                            <label asp-for="ThumbImg" class="font-weight-semibold">Upload Ảnh</label>
                            <input type="file" name="fThumbImg" asp-for="ThumbImg" class="form-control-file" onchange="loadFile(event)" />
                            <span asp-validation-for="ThumbImg" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card" style="background: #F0BF87">
                    <div class="card-body">
                        <label asp-for="Descriptions" class="control-label" style="font-weight :800"></label>
                        <textarea asp-for="Descriptions" class="summernnote"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/_AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/_AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/_AdminAssets/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernnote').summernote({
                fontNames: ['Comic Sans MS'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 350,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
    <script>
        var loadFile = function (event) {
            var image = document.getElementById("output");
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
}
@section Styles {
    <link href="~/_AdminAssets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/_AdminAssets/summernote/summernote.css" rel="stylesheet" />
}

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminCategories/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<WebShopNovel.Models.Category>

@{
    int _current = ViewBag.CurrentPage;
    ViewData["Title"] = "Quản lý danh mục";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/AdminAssets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <span class="breadcrumb-item active">Quản lý danh mục</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row m-b-30">
                <div class="col-lg-8">
                    <form asp-controller="AdminCategories" asp-action="Index">
                        <p>
                            <input type="search" name="searchStr" value="@ViewData["CurrentFilter"]" required />
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </p>
                    </form>

                </div>

                <div class="col-lg-4 text-right">
                    <a asp-controller="AdminCategories" asp-action="Create" class="btn btn-primary">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm Danh mục</span>
                    </a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover e-commerce-table">
                    <thead>
                        <tr>
                            <th>
                                <a asp-action="Index" asp-route-sortOrder="@ViewData["IdSortParm"]">
                                    ID
                                </a>
                            </th>
                            <th>
                                <a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">
                                    Tên danh mục
                                </a>
                            </th>
                            <th class="text-center align-items-center">Mô tả</th>
                            <th>

                                Trạng thái

                            </th>
                            <th class="text-center align-items-center">
                                <a asp-action="Index" asp-route-sortOrder="@ViewData["TitleSortParm"]">
                                    Tiêu đề
                                </a>
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.CateId
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center text-center">
                                            @*<img class="img-fluid rounded" src="~/images/categories/@item.ThumbImg"
                                                style="max-width: 60px" alt="">*@
                                            <h6 class="m-b-0 m-l-10">@item.CategoryName</h6>
                                        </div>
                                    </td>
                                    <td class="text-center align-items-center">@Html.Raw(item.Descriptions)</td>
                                    @if (item.IsPublished)
                                    {
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="badge badge-success badge-dot m-r-10"></div>
                                                <div>In Stock</div>
                                            </div>
                                        </td>
                                    }
                                    else
                                    {
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="badge badge-danger badge-dot m-r-10"></div>
                                                <div>Out of Stock</div>
                                            </div>
                                        </td>
                                    }
                                    <td class="text-center align-items-center">@item.Title</td>
                                    <td>
                                        <a asp-controller="AdminCategories" asp-action="Details" asp-route-id="@item.CateId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-eye"></i>
                                        </a>
                                        <a asp-controller="AdminCategories" asp-action="Edit" asp-route-id="@item.CateId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-edit"></i>
                                        </a>
                                        <a asp-controller="AdminCategories" asp-action="Delete" asp-route-id="@item.CateId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-delete"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <pager class="paper-container" list="@Model" asp-area="Admin" asp-controller="AdminProducts" asp-action="Index"></pager>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <style>
        form {
            position: relative;
            transform: translate(5%,5%);
            transition: all 1s;
            width: 50px;
            height: 50px;
            background: white;
            box-sizing: border-box;
            border-radius: 25px;
            border: 4px solid black;
            padding: 5px;
        }

            form input {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 42.5px;
                line-height: 30px;
                outline: 0;
                border: 0;
                display: none;
                font-size: 1em;
                border-radius: 20px;
                padding: 0 20px;
                background: #CBF6D2;
            }

        .fa {
            box-sizing: border-box;
            padding: 10px;
            width: 42.5px;
            height: 42.5px;
            position: absolute;
            top: 0;
            right: 0;
            border-radius: 50%;
            color: #07051a;
            text-align: center;
            font-size: 1.2em;
            transition: all 1s;
        }

        form:hover,
        form:valid {
            width: 200px;
            cursor: pointer;
        }

            form:hover input,
            form:valid input {
                display: block;
            }

            form:hover .fa,
            form:valid .fa {
                background: #07051a;
                color: white;
            }

        button {
            border: none;
        }
    </style>
}