WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Controllers/AdminProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopNovel.Models;
using PagedList.Core;
using System.Globalization;
using System.IO;
using WebShopNovel.Helpper;
using AspNetCoreHero.ToastNotification.Abstractions;
using System.Data;
using Microsoft.AspNetCore.Authorization;

namespace WebShopNovel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminProductsController : Controller
    {
        private readonly WebNovel _context;
        public static string image;
        public INotyfService _notyfService { get; }

        public AdminProductsController(WebNovel context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        // GET: Admin/AdminProducts
        public IActionResult Index(string sortOrder, string currentFilter, string searchStr, int? page)
        {
            ViewData["CateId"] = new SelectList(_context.Categories, "CateId", "CategoryName");
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName");
            var _product = from m in _context.Products.Include(p => p.Publisher).Include(p => p.Cate) select m;
            //Sort
            ViewData["IdSortParm"] = String.IsNullOrEmpty(sortOrder) ? "id_desc" : "";
            ViewData["DateSortParm"] = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["UnitSortParm"] = sortOrder == "Unit" ? "unit_desc" : "Unit";
            ViewData["CurrentSort"] = sortOrder;
            switch (sortOrder)
            {
                case "id_desc":
                    _product = _product.OrderByDescending(p => p.ProductId);
                    break;
                case "Date":
                    _product = _product.OrderBy(p => p.DateCreated);
                    break;
                case "date_desc":
                    _product = _product.OrderByDescending(p => p.DateCreated);
                    break;
                case "unit_desc":
                    _product = _product.OrderByDescending(p => p.UnitInStock);
                    break;
                case "Unit":
                    _product = _product.OrderBy(p => p.UnitInStock);
                    break;
                default:
                    _product = _product.OrderBy(p => p.ProductId);
                    break;
            }
            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                _product = _product.Where(p => p.ProductName.Contains(searchStr) || p.ProductId.ToString().Contains(searchStr));
            }
            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 5;
            PagedList<Product> models = new PagedList<Product>(_product, pageNo, pageSize);
            ViewBag.CurrentPage = pageNo;

            return View(models);
        }

        // GET: Admin/AdminProducts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Publisher)
                .Include(p => p.Cate)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Admin/AdminProducts/Create
        public IActionResult Create()
        {
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName");
            ViewData["CateId"] = new SelectList(_context.Categories, "CateId", "CategoryName");
            return View();
        }

        // POST: Admin/AdminProducts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ProductId,ProductName,ShortDesc,Descriptions,CateId,Price,Discount,ThumbImg,Video,DateCreated,DateModified,IsBestsellers,Homeflag,IsActived,Tag,Title,Alias,UnitInStock,PublisherId,SalesPrice")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumbImg)
        {
            if (ModelState.IsValid)
            {
                product.ProductName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(product.ProductName);
                if (fThumbImg != null)
                {
                    string extennsion = Path.GetExtension(fThumbImg.FileName);
                    image = Utilities.ToUrlFriendly(product.ProductName) + extennsion;
                    product.ThumbImg = await Utilities.UploadFile(fThumbImg, @"products", image.ToLower());
                }
                if (string.IsNullOrEmpty(product.ThumbImg)) product.ThumbImg = "thumb-6.jpg";
                product.Alias = Utilities.ToUrlFriendly(product.ProductName);
                product.DateCreated = DateTime.Now;
                product.DateModified = DateTime.Now;
                product.SalesPrice = product.Price.Value - (product.Price.Value * (product.Discount.Value) / 100);
                if (product.Discount == null)
                {
                    product.Discount = 0;
                }
                _context.Add(product);
                _notyfService.Success("Thêm thành công!");
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName", product.PublisherId);
            ViewData["CateId"] = new SelectList(_context.Categories, "CateId", "CategoryName", product.CateId);
            return View(product);
        }

        // GET: Admin/AdminProducts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName", product.PublisherId);
            ViewData["CateId"] = new SelectList(_context.Categories, "CateId", "CategoryName", product.CateId);
            return View(product);
        }

        // POST: Admin/AdminProducts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ProductId,ProductName,ShortDesc,Descriptions,CateId,Price,Discount,ThumbImg,Video,DateCreated,DateModified,IsBestsellers,Homeflag,IsActived,Tag,Title,Alias,UnitInStock,PublisherId,SalesPrice")] Product product, Microsoft.AspNetCore.Http.IFormFile fThumbImg)
        {
            if (id != product.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.ProductName = CultureInfo.CurrentCulture.TextInfo.ToTitleCase(product.ProductName);
                    if (fThumbImg != null)
                    {
                        string extennsion = Path.GetExtension(fThumbImg.FileName);
                        image = Utilities.ToUrlFriendly(product.ProductName) + extennsion;
                        product.ThumbImg = await Utilities.UploadFile(fThumbImg, @"products", image.ToLower());
                    }
                    if (string.IsNullOrEmpty(product.ThumbImg)) product.ThumbImg = "thumb-6.jpg";
                    product.Alias = Utilities.ToUrlFriendly(product.ProductName);
                    product.DateModified = DateTime.Now;
                    product.SalesPrice = product.Price.Value - (product.Price.Value * (product.Discount.Value) / 100);
                    if (product.Discount == null)
                    {
                        product.Discount = 0;
                    }
                    _context.Update(product);
                    _notyfService.Success("Sửa thành công!");
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["PublisherId"] = new SelectList(_context.Publishers, "PublisherId", "PublisherName", product.PublisherId);
            ViewData["CateId"] = new SelectList(_context.Categories, "CateId", "CategoryName", product.CateId);
            return View(product);
        }

        [Authorize(Roles = "Admin")]
        // GET: Admin/AdminProducts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Publisher)
                .Include(p => p.Cate)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminProducts/BestSeller.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<WebShopNovel.Models.Product>

@{
    int _current = ViewBag.CurrentPage;
    ViewData["Title"] = "Sản phầm bán chạy - Trang "+_current;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/AdminAssets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="main-content">
    <div class="page-header">
        
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <span class="breadcrumb-item active">Quản lý sản phẩm</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row m-b-30">
                <div class="col-lg-8">
                    <form asp-controller="AdminProducts" asp-action="Index">
                        <p>
                            <input type="search" name="searchStr" value="@ViewData["CurrentFilter"]" required />
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </p>
                    </form>

                </div>

                <div class="col-lg-4 text-right">
                    <a asp-controller="AdminProducts" asp-action="Create" class="btn btn-primary">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm sản phẩm</span>
                    </a>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover e-commerce-table">
                    <thead>
                        <tr>
                            <th>
                                <a @*asp-action="Index"*@ asp-route-sortOrder="@ViewData["IdSortParm"]">
                                    ID
                                </a>
                            </th>
                            <th class="text-center align-items-center">
                                Tên sản phẩm
                            </th>
                            <th class="text-center align-items-center">Danh mục</th>
                            <th class="text-center align-items-center">Thương hiệu</th>
                            <th>Giá</th>
                            <th class="text-center align-items-center">
                                <a @*asp-action="Index"*@ asp-route-sortOrder="@ViewData["UnitSortParm"]">
                                    Kho
                                </a>
                            </th>
                            <th>Trạng thái</th>
                            <th class="text-center align-items-center">Bán chạy</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td>
                                        @item.ProductId
                                    </td>
                                    <td>
                                        <div class="d-flex align-items-center text-center">
                                            <img class="img-fluid rounded" src="~/images/products/@item.ThumbImg"
                                                 style="max-width: 60px" alt="">
                                            <h6 class="m-b-0 m-l-10">@item.ProductName</h6>
                                        </div>
                                    </td>
                                    <td class="text-center align-items-center">@item.Cate.CategoryName</td>
                                    <td class="text-center align-items-center">@item.Publisher.PublisherName</td>
                                    <td>@item.Price.Value.ToString("#,##0") VNĐ</td>
                                    <td class="text-center align-items-center">@item.UnitInStock</td>
                                    @if (item.IsActived && item.UnitInStock > 0)
                                    {
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="badge badge-success badge-dot m-r-10"></div>
                                                <div>In Stock</div>
                                            </div>
                                        </td>
                                    }
                                    else
                                    {
                                        <td>
                                            <div class="d-flex align-items-center">
                                                <div class="badge badge-danger badge-dot m-r-10"></div>
                                                <div>Out of Stock</div>
                                            </div>
                                        </td>
                                    }
                                    @if (item.IsBestsellers)
                                    {
                                        <td class="text-center align-items-center">
                                            <i class="fab fa-hotjar"></i>
                                        </td>
                                    }
                                    else
                                    {
                                        <td class="text-center align-items-center">
                                            <i class="fas fa-temperature-low"></i>
                                        </td>
                                    }
                                    <td>
                                        <a asp-controller="AdminProducts" asp-action="Details" asp-route-id="@item.ProductId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-eye"></i>
                                        </a>
                                        <a asp-controller="AdminProducts" asp-action="Edit" asp-route-id="@item.ProductId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-edit"></i>
                                        </a>
                                        @*<button type="button" class="btn btn-icon btn-hover btn-sm btn-rounded" data-toggle="modal" data-target="#exampleModalCenter">
                                                <i class="anticon anticon-delete"></i>
                                            </button>*@
                                        <a asp-controller="AdminProducts" asp-action="Delete" asp-route-id="@item.ProductId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-delete"></i>
                                        </a>
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <pager class="paper-container" list="@Model" asp-area="Admin" asp-controller="AdminProducts" asp-action="Index"></pager>
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModalCenter">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalCenterTitle">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal">
                    <i class="anticon anticon-close"></i>
                </button>
            </div>
            <div class="modal-body">
                Bạn có chắc muốn xóa nó chứ?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-danger">Xóa</button>
            </div>
        </div>
    </div>
</div>
@section Styles {
    <style>
        form {
            position: relative;
            transform: translate(5%,5%);
            transition: all 1s;
            width: 50px;
            height: 50px;
            background: white;
            box-sizing: border-box;
            border-radius: 25px;
            border: 4px solid black;
            padding: 5px;
        }

            form input {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 42.5px;
                line-height: 30px;
                outline: 0;
                border: 0;
                display: none;
                font-size: 1em;
                border-radius: 20px;
                padding: 0 20px;
                background: #CBF6D2;
            }

        .fa {
            box-sizing: border-box;
            padding: 10px;
            width: 42.5px;
            height: 42.5px;
            position: absolute;
            top: 0;
            right: 0;
            border-radius: 50%;
            color: #07051a;
            text-align: center;
            font-size: 1.2em;
            transition: all 1s;
        }

        form:hover,
        form:valid {
            width: 200px;
            cursor: pointer;
        }

            form:hover input,
            form:valid input {
                display: block;
            }

            form:hover .fa,
            form:valid .fa {
                background: #07051a;
                color: white;
            }

        button {
            border: none;
        }
    </style>
}

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminProducts/Create.cshtml
@model WebShopNovel.Models.Product

@{
    ViewData["Title"] = "Thêm sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


<div class="main-content">
    <form asp-controller="AdminProducts" asp-action="Create" method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="page-header no-gutters has-tab">
            <div class="d-md-flex m-b-15 align-items-center justify-content-between">
                <div class="media align-items-center m-b-15">
                    <div class="avatar avatar-image rounded" style="height: 165px; width: 165px;">
                        <img src="~/_AdminAssets/images/others/thumb-16.jpg" style="border-radius:20px;" alt="" id="output">
                    </div>
                    <div class="m-l-15">
                        <h4 class="m-b-0">Unknown</h4>
                        <p class="text-muted m-b-0">ID: #Unknown</p>
                    </div>
                </div>
                <div class="m-b-15">
                    <div class="form-group">
                        <button type="submit" class="btn btn-primary">
                            <i class="anticon anticon-save"></i>
                            <span>Tạo</span>
                        </button>
                    </div>
                    <div>
                        <a asp-action="Index" type="button" class="btn btn-dark">Trở về</a>
                    </div>
                </div>
            </div>
            <ul class="nav nav-tabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#product-edit-basic">Thông tin cơ bản</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-option">Thông tin tùy chọn</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#product-edit-description">Mô tả</a>
                </li>
            </ul>
        </div>
        <div class="tab-content m-t-15">
            <div class="tab-pane fade show active" id="product-edit-basic">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="ProductName" class="control-label">Tên sản phẩm</label>
                            <input asp-for="ProductName" class="form-control" />
                            <span asp-validation-for="ProductName" class="text-danger"></span>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-4 ">
                                <label asp-for="Price" class="control-label">Giá gốc</label>
                                <input asp-for="Price" ng-model="pr.cost" class="form-control"/>
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="SalesPrice" class="control-label">Giá bán</label>
                                <input asp-for="SalesPrice" class="form-control" disabled />
                                <span asp-validation-for="Price" class="text-danger"></span>
                            </div>
                            <div class="form-group col-md-4">
                                <label asp-for="Discount" class="control-label"></label>
                                <input asp-for="Discount" ng-model="pr.markup" class="form-control" />
                                <span asp-validation-for="Discount" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="row">
                            <div class="form-group col-md-3">
                                <label asp-for="CateId" class="control-label">Danh mục</label>
                                <select asp-for="CateId" class="form-control" asp-items="ViewBag.CateId"></select>
                            </div>
                            <div class="form-group">
                                <label asp-for="PublisherId" class="control-label">Nhà xuất bản</label>
                                <select asp-for="PublisherId" class="form-control" asp-items="ViewBag.PublisherID"></select>
                            </div>
                            <div class="form-group col-md-6">
                                <label asp-for="UnitInStock" class="control-label">Tồn kho</label>
                                <input asp-for="UnitInStock" class="form-control" />
                                <span asp-validation-for="UnitInStock" class="text-danger"></span>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="Title" class="control-label">Danh mục (Nhật Bản: JPNovel, Trung Quốc: CNNovel, Hàn Quốc: KRNovel)</label>
                            <input asp-for="Title" class="form-control" />
                            <span asp-validation-for="Title" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <label asp-for="ThumbImg" class="font-weight-semibold">Upload Ảnh</label>
                            <input type="file" name="fThumbImg" asp-for="ThumbImg" class="form-control-file" onchange="loadFile(event)" />
                            <span asp-validation-for="ThumbImg" class="text-danger"></span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-option">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            <label asp-for="Tag" class="control-label"></label>
                            <input asp-for="Tag" class="form-control" />
                            <span asp-validation-for="Tag" class="text-danger"></span>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="IsActived" checked="" />
                                <label for="IsActived"></label>
                            </div>
                            <label>Actived</label>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="Homeflag" checked="" />
                                <label for="Homeflag"></label>
                            </div>
                            <label>Homeflag</label>
                        </div>
                        <div class="form-group d-flex align-items-center">
                            <div class="switch m-r-10">
                                <input type="checkbox" asp-for="IsBestsellers" checked="" />
                                <label for="IsBestsellers"></label>
                            </div>
                            <label>BestSeller</label>
                        </div>
                    </div>
                </div>
            </div>
            <div class="tab-pane fade" id="product-edit-description">
                <div class="card" style="background: #F0BF87">
                    <div class="card-body">
                        <label asp-for="Descriptions" class="control-label" style="font-weight :800"></label>
                        <textarea asp-for="Descriptions" class="summernnote"></textarea>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/_AdminAssets/js/pages/e-commerce-product-edit.js"></script>
    <script src="~/_AdminAssets/vendors/select2/select2.min.js"></script>
    <script src="~/_AdminAssets/summernote/summernote-bs4.js"></script>
    <script>
        jQuery(document).ready(function () {
            $('.summernnote').summernote({
                fontNames: ['Comic Sans MS'],
                styleTags: ['p', 'h1', 'h2', 'h3', 'h4', 'h5'],
                height: 350,
                minHeight: null,
                maxHeight: null,
                focus: true
            });
        });
    </script>
    <script>
        var loadFile = function (event) {
            var image = document.getElementById("output");
            image.src = URL.createObjectURL(event.target.files[0]);
        };
    </script>
}
@section Styles {
    <link href="~/_AdminAssets/summernote/summernote-bs4.css" rel="stylesheet" />
    <link href="~/_AdminAssets/summernote/summernote.css" rel="stylesheet" />
}