WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Controllers/AdminOrdersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebShopNovel.Models;
using PagedList.Core;
using Microsoft.AspNetCore.Authorization;

namespace WebShopNovel.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminOrdersController : Controller
    {
        private readonly WebNovel _context;

        public AdminOrdersController(WebNovel context)
        {
         
            _context = context;
        }

        #region index
        public IActionResult Index(string searchStr, int? page)
        {
            //chưa duyệt
            var ecommerceVer2Context = from m in _context.Orders.Include(o => o.Customer).Include(o => o.TransactionStatus).Where(o => o.TransactionStatusId == 1).OrderByDescending(x => x.OrderDate) select m;
            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                ecommerceVer2Context = ecommerceVer2Context.Where(p => p.OrderId.ToString().Contains(searchStr) || p.CustomerId.ToString().Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 15;
            ViewBag.CurrentPage = pageNo;
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName");
            PagedList<Order> models = new PagedList<Order>(ecommerceVer2Context, pageNo, pageSize);
            return View(models);
        }

        public IActionResult Index4(string searchStr, int? page)
        {
            //đã duyệt
            var ecommerceVer2Context = from m in _context.Orders.Include(o => o.Customer).Include(o => o.TransactionStatus).Where(o => o.TransactionStatusId == 2).OrderByDescending(x => x.OrderDate) select m;
            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                ecommerceVer2Context = ecommerceVer2Context.Where(p => p.OrderId.ToString().Contains(searchStr) || p.CustomerId.ToString().Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 15;
            ViewBag.CurrentPage = pageNo;
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName");
            PagedList<Order> models = new PagedList<Order>(ecommerceVer2Context, pageNo, pageSize);
            return View(models);
        }

        public IActionResult Index1(string searchStr, int? page)
        {
            //Đang chuyển
            var DeliveringProduct = from m in _context.Orders.Include(o => o.Customer).Include(o => o.TransactionStatus).Where(o => o.TransactionStatusId == 3).OrderByDescending(x => x.OrderDate) select m;
            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                DeliveringProduct = DeliveringProduct.Where(p => p.OrderId.ToString().Contains(searchStr) || p.CustomerId.ToString().Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 15;
            ViewBag.CurrentPage = pageNo;
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName");
            PagedList<Order> models = new PagedList<Order>(DeliveringProduct, pageNo, pageSize);
            return View(models);
        }

        public IActionResult Index2(string searchStr, int? page)
        {
            //Đã giao
            var DeliveredProduct = from m in _context.Orders.Include(o => o.Customer).Include(o => o.TransactionStatus).Where(o => o.TransactionStatusId == 5).OrderByDescending(x => x.OrderDate) select m;
            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                DeliveredProduct = DeliveredProduct.Where(p => p.OrderId.ToString().Contains(searchStr) || p.CustomerId.ToString().Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 15;
            ViewBag.CurrentPage = pageNo;
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName");
            PagedList<Order> models = new PagedList<Order>(DeliveredProduct, pageNo, pageSize);
            return View(models);
        }

        public IActionResult Index3(string searchStr, int? page)
        {
            //Đã trả tiền
            var paidProduct = from m in _context.Orders.Include(o => o.Customer).Include(o => o.TransactionStatus).Where(o => o.IsPaid == true).OrderByDescending(x => x.OrderDate) select m;
            //Search
            ViewData["CurrentFilter"] = searchStr;
            if (!String.IsNullOrEmpty(searchStr))
            {
                paidProduct = paidProduct.Where(p => p.OrderId.ToString().Contains(searchStr) || p.CustomerId.ToString().Contains(searchStr));
            }

            //Paginate
            var pageNo = page == null || page <= 0 ? 1 : page.Value;
            var pageSize = 15;
            ViewBag.CurrentPage = pageNo;
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName");
            PagedList<Order> models = new PagedList<Order>(paidProduct, pageNo, pageSize);
            return View(models);
        }
        #endregion
        #region details
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders
                .Include(o => o.Customer)
                .Include(o => o.TransactionStatus)
                .Where(o => o.IsDeleted == false)
                .FirstOrDefaultAsync(m => m.OrderId == id);
            if (order == null)
            {
                return NotFound();
            }

            var chitietdohang = _context.OrderDetails
                .AsNoTracking()
                .Include(x => x.Product)
                .Where(x => x.OrderId == order.OrderId)
                .OrderBy(x => x.OrderDetailId)
                .ToList();
            ViewBag.ChiTiet = chitietdohang;
            return View(order);
        }
        #endregion
        #region Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName");
            ViewData["TransactionStatusId"] = new SelectList(_context.TransactStatuses, "TransactionStatusId", "Descriptions");
            return View();
        }

        // POST: Admin/AdminOrders/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactionStatusId,IsDeleted,IsPaid,PaymentDate,PaymentId,Note,TotalMoney,Address,Province,District,Ward")] Order order)
        {
            if (ModelState.IsValid)
            {
                _context.Add(order);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName", order.CustomerId);
            ViewData["TransactionStatusId"] = new SelectList(_context.TransactStatuses, "TransactionStatusId", "Descriptions", order.TransactionStatusId);
            return View(order);
        }
        #endregion
        #region Edit
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var order = await _context.Orders.FindAsync(id);
            if (order == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(_context.Customers, "CustommerId", "FullName", order.CustomerId);
            ViewData["TransactionStatusId"] = new SelectList(_context.TransactStatuses, "TransactionStatusId", "Descriptions", order.TransactionStatusId);
            return View(order);
        }

        // POST: Admin/AdminOrders/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OrderId,CustomerId,OrderDate,ShipDate,TransactionStatusId,IsDeleted,IsPaid,PaymentDate,PaymentId,Note,TotalMoney,Address,Province,District,Ward")] Order order)
        {
            if (id != order.OrderId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    var donhang = _context.Orders.AsNoTracking().Include(x => x.Customer).Where(x=>x.OrderId==id).FirstOrDefault();
                    if (donhang != null)
                    {
                        donhang.IsPaid = order.IsPaid;
                        donhang.IsDeleted = order.IsDeleted;
                        donhang.TransactionStatusId = order.TransactionStatusId;
                        donhang.OrderDate = order.OrderDate;
                        //Khai báo Chitietdonhang có Id = donhang.Id
                        var orderdetail = _context.OrderDetails
                                .AsNoTracking()

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminOrders/Details.cshtml
@model WebShopNovel.Models.Order

@{
    ViewData["Title"] = "Chi Tiết Đơn Hàng #" + Model.OrderId;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
    List<OrderDetail> orderDetails = ViewBag.ChiTiet;
}

<div class="main-content">
    <div class="container">
        <div class="card">
            <div class="card-body">
                <div id="invoice" class="p-h-30">
                    <div class="m-t-15 lh-2">
                        <div class="inline-block">
                            <img class="img-fluid" src="~/_AdminAssets/images/logo/logo.png" alt="" style="height:130px;width:260px;">
                            <address class="p-l-10">
                                <span class="font-weight-semibold text-dark">WebShopNovel, Inc.</span><br>
                                <span>9498 Harvard Street</span><br>
                                <span>Fairfield, Chicago Town 06824</span><br>
                                <abbr class="text-dark" title="Phone">Phone:</abbr>
                                <span>(+84) 968-454-617</span>
                            </address>
                        </div>
                        <div class="float-right">
                            <h2>INVOICE</h2>
                        </div>
                    </div>
                    <div class="row m-t-20 lh-2">
                        <div class="col-sm-9">
                            <h3 class="p-l-10 m-t-10">Invoice To:</h3>
                            <address class="p-l-10 m-t-10">
                                <div class="row">
                                    <div class="col-md-4">
                                        <span><a style="font-weight: 800; margin-right:10px;">Họ tên khách hàng:</a></span><br>
                                        <span><a style="font-weight: 800; margin-right: 10px;">Địa chỉ:</a></span><br>
                                        <span><a style="font-weight: 800; margin-right: 10px;">Số điện thoại:</a></span><br>
                                        <span><a style="font-weight: 800; margin-right: 10px;">Tỉnh/Thành phố:</a></span><br>
                                        <span><a style="font-weight: 800; margin-right: 10px;">Quận huyện:</a></span><br>
                                        <span><a style="font-weight: 800; margin-right: 10px; ">Phường xã:</a></span><br>
                                    </div>
                                    <div class="col-md-5">
                                        <span>@Model.Customer.FullName</span><br>
                                        <span>@Model.Address</span><br>
                                        <span>@Model.Customer.Phone</span><br>
                                        <span>@Model.Province</span><br>
                                        <span>@Model.District</span><br>
                                        <span>@Model.Ward</span><br>
                                    </div>
                                </div>
                            </address>
                        </div>
                        <div class="col-sm-3">
                            <div class="m-t-80">
                                <div class="text-dark text-uppercase d-inline-block">
                                    <span class="font-weight-semibold text-dark">Invoice No :</span>
                                </div>
                                <div class="float-right">#@Model.OrderId</div>
                            </div>
                            <div class="text-dark text-uppercase d-inline-block">
                                <span class="font-weight-semibold text-dark">Date :</span>
                            </div>
                            <div class="float-right">@Model.OrderDate</div>
                        </div>
                    </div>
                    <div class="m-t-20">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>No.</th>
                                        <th>Items</th>
                                        <th>Quantity</th>
                                        <th>Price</th>
                                        <th>Total</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (orderDetails != null && orderDetails.Count() > 0)
                                    {
                                        int i = 1;
                                        foreach (var item in orderDetails)
                                        {
                                            <tr>
                                                <td>@i</td>
                                                <td>@item.Product.ProductName</td>
                                                <td>@item.Quantity</td>
                                                <td>@item.Price.Value.ToString("#,##0") VNĐ</td>
                                                <td>@item.Total.Value.ToString("#,##0") VNĐ</td>
                                            </tr>
                                            i++;
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                        <div class="row m-t-30 lh-1-8">
                            <div class="col-sm-12">
                                <div class="container">
                                    <div class="row">
                                        <div class="col-md-9">
                                            <a class="btn btn-block btn-primary col-md-3" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index" ><i class="fas fa-arrow-left" style="margin-right:10px;"></i>Quay lại</a>
                                        </div>
                                        <div class="float-right text-right col-md-3">
                                            <h3><span class="font-weight-semibold text-dark">Total :</span> @Model.TotalMoney.Value.ToString("#,##0") VNĐ</h3>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row m-v-20">
                            <div class="col-sm-6">
                                <img class="img-fluid text-opacity m-t-5" width="100" src="assets/images/logo/logo.png" alt="">
                            </div>
                            <div class="col-sm-6 text-right">
                                <small><span class="font-weight-semibold text-dark">Phone:</span> (+84) 968-454-617</small>
                                <br>
                                <small>support@themenate.com</small>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminOrders/Index.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<WebShopNovel.Models.Order>

@{
    int _current = ViewBag.CurrentPage;
    ViewData["Title"] = "Đơn hàng chưa duyệt - Trang "+ _current;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/AdminAssets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <span class="breadcrumb-item active">Quản lý Đơn Hàng</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row m-b-30">
                <div class="col-lg-8">
                    <form asp-controller="AdminOrders" asp-action="Index">
                        <p>
                            <input type="search" name="searchStr" value="@ViewData["CurrentFilter"]" required />
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </p>
                    </form>

                </div>

                <div class="col-lg-4 text-right">
                    @*<a asp-controller="AdminOrders" asp-action="Create" class="btn btn-primary">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm Đơn Hàng</span>
                    </a>*@
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover e-commerce-table">
                    <thead>
                        <tr>
                            <th class="text-center align-items-center">
                                ID
                            </th>
                            <th class="text-center align-items-center">
                                Đơn hàng
                            </th>
                            <th class="text-center align-items-center">Mô tả</th>
                            <th class="text-center align-items-center">
                                Trạng thái
                            </th>
                            <th class="text-center align-items-center">
                                Ngày mua
                            </th>
                            <th class="text-center align-items-center">
                                Tổng tiền
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td class="text-center align-items-center">
                                        @item.OrderId
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.Customer.FullName
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.TransactionStatus.Descriptions
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.IsPaid
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.OrderDate
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.TotalMoney.Value.ToString("#,##0") VNĐ
                                    </td>
                                    <td>
                                        <a asp-controller="AdminOrders" asp-action="Details" asp-route-id="@item.OrderId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-eye"></i>
                                        </a>
                                        <a asp-controller="AdminOrders" asp-action="Edit" asp-route-id="@item.OrderId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-edit"></i>
                                        </a>
                                        @*<a asp-controller="AdminOrders" asp-action="Delete" asp-route-id="@item.OrderId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-delete"></i>
                                        </a>*@
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <pager class="paper-container" list="@Model" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index"></pager>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <style>
        form {
            position: relative;
            transform: translate(5%,5%);
            transition: all 1s;
            width: 50px;
            height: 50px;
            background: white;
            box-sizing: border-box;
            border-radius: 25px;
            border: 4px solid black;
            padding: 5px;
        }

            form input {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 42.5px;
                line-height: 30px;
                outline: 0;
                border: 0;
                display: none;
                font-size: 1em;
                border-radius: 20px;
                padding: 0 20px;
                background: #CBF6D2;
            }

        .fa {
            box-sizing: border-box;
            padding: 10px;
            width: 42.5px;
            height: 42.5px;
            position: absolute;
            top: 0;
            right: 0;
            border-radius: 50%;
            color: #07051a;
            text-align: center;
            font-size: 1.2em;
            transition: all 1s;
        }

        form:hover,
        form:valid {
            width: 200px;
            cursor: pointer;
        }

            form:hover input,
            form:valid input {
                display: block;
            }

            form:hover .fa,
            form:valid .fa {
                background: #07051a;
                color: white;
            }

        button {
            border: none;
        }
    </style>
}

WebShop_LightNovel/WebShop_LightNovel/Areas/Admin/Views/AdminOrders/Index1.cshtml
@using PagedList.Core.Mvc
@model PagedList.Core.IPagedList<WebShopNovel.Models.Order>

@{
    int _current = ViewBag.CurrentPage;
    ViewData["Title"] = "Đơn hàng đang vận chuyển - Trang " +_current;
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
<link href="~/AdminAssets/vendors/datatables/dataTables.bootstrap.min.css" rel="stylesheet">
<div class="main-content">
    <div class="page-header">
        <div class="header-sub-title">
            <nav class="breadcrumb breadcrumb-dash">
                <a asp-controller="Home" asp-action="Index" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Home</a>
                <span class="breadcrumb-item active">Quản lý Đơn Hàng</span>
            </nav>
        </div>
    </div>
    <div class="card">
        <div class="card-body">
            <div class="row m-b-30">
                <div class="col-lg-8">
                    <form asp-controller="AdminOrders" asp-action="Index">
                        <p>
                            <input type="search" name="searchStr" value="@ViewData["CurrentFilter"]" required />
                            <button type="submit"><i class="fa fa-search"></i></button>
                        </p>
                    </form>

                </div>

                <div class="col-lg-4 text-right">
                    @*<a asp-controller="AdminOrders" asp-action="Create" class="btn btn-primary">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm Đơn Hàng</span>
                    </a>*@
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover e-commerce-table">
                    <thead>
                        <tr>
                            <th class="text-center align-items-center">
                                ID
                            </th>
                            <th class="text-center align-items-center">
                                Đơn hàng
                            </th>
                            <th class="text-center align-items-center">Mô tả</th>
                            <th class="text-center align-items-center">
                                Trạng thái
                            </th>
                            <th class="text-center align-items-center">
                                Ngày mua
                            </th>
                            <th class="text-center align-items-center">
                                Tổng tiền
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @if (Model != null)
                        {
                            foreach (var item in Model)
                            {
                                <tr>
                                    <td class="text-center align-items-center">
                                        @item.OrderId
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.Customer.FullName
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.TransactionStatus.Descriptions
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.IsPaid
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.OrderDate
                                    </td>
                                    <td class="text-center align-items-center">
                                        @item.TotalMoney.Value.ToString("#,##0") VNĐ
                                    </td>
                                    <td>
                                        <a asp-controller="AdminOrders" asp-action="Details" asp-route-id="@item.OrderId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-eye"></i>
                                        </a>
                                        <a asp-controller="AdminOrders" asp-action="Edit" asp-route-id="@item.OrderId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-edit"></i>
                                        </a>
                                        @*<a asp-controller="AdminOrders" asp-action="Delete" asp-route-id="@item.OrderId" class="btn btn-icon btn-hover btn-sm btn-rounded">
                                            <i class="anticon anticon-delete"></i>
                                        </a>*@
                                    </td>
                                </tr>
                            }
                        }
                    </tbody>
                </table>
                <pager class="paper-container" list="@Model" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index1"></pager>
            </div>
        </div>
    </div>
</div>

@section Styles {
    <style>
        form {
            position: relative;
            transform: translate(5%,5%);
            transition: all 1s;
            width: 50px;
            height: 50px;
            background: white;
            box-sizing: border-box;
            border-radius: 25px;
            border: 4px solid black;
            padding: 5px;
        }

            form input {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 42.5px;
                line-height: 30px;
                outline: 0;
                border: 0;
                display: none;
                font-size: 1em;
                border-radius: 20px;
                padding: 0 20px;
                background: #CBF6D2;
            }

        .fa {
            box-sizing: border-box;
            padding: 10px;
            width: 42.5px;
            height: 42.5px;
            position: absolute;
            top: 0;
            right: 0;
            border-radius: 50%;
            color: #07051a;
            text-align: center;
            font-size: 1.2em;
            transition: all 1s;
        }

        form:hover,
        form:valid {
            width: 200px;
            cursor: pointer;
        }

            form:hover input,
            form:valid input {
                display: block;
            }

            form:hover .fa,
            form:valid .fa {
                background: #07051a;
                color: white;
            }

        button {
            border: none;
        }
    </style>
}